"""Amazon UK parser stub (PR K).

STUB: body generated by the PR H capability materialiser. UK retail
source — prices are already in GBP, no FX conversion needed.
"""
from __future__ import annotations

from typing import Any, Dict, List

SEED_CAPABILITY_METADATA: Dict[str, Any] = {
    "name":            "procurement_parser_amazon_uk",
    "type":            "concept",
    "capability_type": "html_parser",
    "description": (
        "Parse an Amazon UK search-results or product page into a list of "
        "hardware dicts. Extract per listing: name (str), cpu (str), "
        "cpu_passmark (int, look up if absent), tdp_w (float), idle_w "
        "(float if known), ram_gb (int), storage_gb (int), price_gbp "
        "(float, GBP), url (str). Prices are GBP (no FX). Return list[dict]; "
        "skip rows missing name or cpu."
    ),
    "source_url":    "https://www.amazon.co.uk/",
    "runtime_mode":  "stub",
    "language":      "python",
    "methods":       ["parse"],
    "is_async":      False,
    "args":          ["html"],
    "provenance":    "fresh_blood_seed",
    "seed_hash":     "procurement:amazon_uk:v1",
}


def parse(html: str) -> List[Dict[str, Any]]:
    """Parse an Amazon UK page into hardware rows priced in GBP.

    :param html: raw HTML of an Amazon UK search results / product page.
    :returns: list of dicts with keys name, cpu, cpu_passmark, tdp_w,
        idle_w, ram_gb, storage_gb, price_gbp, currency_orig='GBP', url.

    Not yet materialised — see :data:`SEED_CAPABILITY_METADATA`.
    """
    raise NotImplementedError(
        "amazon_uk.parse is a materialiser stub; see "
        "SEED_CAPABILITY_METADATA for the generation brief"
    )


def seed_fallback() -> List[Dict[str, Any]]:
    """Hand-written known Amazon UK listings (GBP)."""
    return [
        {
            "name": "Beelink SER8",
            "url": "https://www.amazon.co.uk/dp/B0D3J9X8K1",
            "cpu": "AMD Ryzen 7 8845HS",
            "cpu_passmark": 28500,
            "tdp_w": 54.0,
            "idle_w": 11.0,
            "ram_gb": 32,
            "storage_gb": 1000,
            "currency_orig": "GBP",
            "price_orig": 579.0,
            "price_gbp": 579.0,
        },
        {
            "name": "Minisforum UM790 Pro",
            "url": "https://www.amazon.co.uk/dp/B0C9YKW7ML",
            "cpu": "AMD Ryzen 9 7940HS",
            "cpu_passmark": 28000,
            "tdp_w": 65.0,
            "idle_w": 13.0,
            "ram_gb": 32,
            "storage_gb": 1000,
            "currency_orig": "GBP",
            "price_orig": 629.0,
            "price_gbp": 629.0,
        },
    ]


__all__ = ["SEED_CAPABILITY_METADATA", "parse", "seed_fallback"]
