"""Newegg (US) parser stub (PR K).

STUB: body generated by the PR H capability materialiser. US retail
source — prices are published in USD and the researcher normalises them
to GBP using the FX rate from :mod:`components.procurement.config`.
"""
from __future__ import annotations

from typing import Any, Dict, List

SEED_CAPABILITY_METADATA: Dict[str, Any] = {
    "name":            "procurement_parser_newegg_us",
    "type":            "concept",
    "capability_type": "html_parser",
    "description": (
        "Parse a Newegg (US) search-results or product page into a list of "
        "hardware dicts. Extract per listing: name (str), cpu (str), "
        "cpu_passmark (int, look up if absent), tdp_w (float), idle_w "
        "(float if known), ram_gb (int), storage_gb (int), price_orig "
        "(float, USD), url (str). Set currency_orig='USD'; the researcher "
        "converts to GBP. Return list[dict]; skip rows missing name or cpu."
    ),
    "source_url":    "https://www.newegg.com/",
    "runtime_mode":  "stub",
    "language":      "python",
    "methods":       ["parse"],
    "is_async":      False,
    "args":          ["html"],
    "provenance":    "fresh_blood_seed",
    "seed_hash":     "procurement:newegg_us:v1",
}


def parse(html: str) -> List[Dict[str, Any]]:
    """Parse a Newegg (US) page into hardware rows priced in USD.

    :param html: raw HTML of a Newegg search results / product page.
    :returns: list of dicts with keys name, cpu, cpu_passmark, tdp_w,
        idle_w, ram_gb, storage_gb, price_orig (USD), currency_orig, url.

    Not yet materialised — see :data:`SEED_CAPABILITY_METADATA`.
    """
    raise NotImplementedError(
        "newegg_us.parse is a materialiser stub; see "
        "SEED_CAPABILITY_METADATA for the generation brief"
    )


def seed_fallback() -> List[Dict[str, Any]]:
    """Hand-written known Newegg US listings (USD)."""
    return [
        {
            "name": "Beelink SER8",
            "url": "https://www.newegg.com/beelink-ser8/p/N82E16883107001",
            "cpu": "AMD Ryzen 7 8845HS",
            "cpu_passmark": 28500,
            "tdp_w": 54.0,
            "idle_w": 11.0,
            "ram_gb": 32,
            "storage_gb": 1000,
            "currency_orig": "USD",
            "price_orig": 729.0,
        },
        {
            "name": "Minisforum MS-01",
            "url": "https://www.newegg.com/minisforum-ms-01/p/N82E16883107002",
            "cpu": "Intel Core i9-13900H",
            "cpu_passmark": 28000,
            "tdp_w": 45.0,
            "idle_w": 15.0,
            "ram_gb": 32,
            "storage_gb": 1000,
            "currency_orig": "USD",
            "price_orig": 819.0,
        },
    ]


__all__ = ["SEED_CAPABILITY_METADATA", "parse", "seed_fallback"]
