"""TechPowerUp CPU DB parser stub (PR K).

STUB: body generated by the PR H capability materialiser. This is a
spec source (PassMark + TDP), not a retail source, so rows carry no
retail price (``price_gbp`` is None). The researcher uses these rows to
enrich / cross-check CPU PassMark + TDP for boxes priced elsewhere, and
:func:`seed_fallback` seeds a few common APU specs.
"""
from __future__ import annotations

from typing import Any, Dict, List

SEED_CAPABILITY_METADATA: Dict[str, Any] = {
    "name":            "procurement_parser_techpowerup",
    "type":            "concept",
    "capability_type": "html_parser",
    "description": (
        "Parse a TechPowerUp CPU database page into a list of CPU spec "
        "dicts. Extract per CPU: cpu (str model name), cpu_passmark (int), "
        "tdp_w (float), idle_w (float if published else None). No retail "
        "price. Return list[dict]; skip rows missing cpu."
    ),
    "source_url":    "https://www.techpowerup.com/cpu-specs/",
    "runtime_mode":  "stub",
    "language":      "python",
    "methods":       ["parse"],
    "is_async":      False,
    "args":          ["html"],
    "provenance":    "fresh_blood_seed",
    "seed_hash":     "procurement:techpowerup:v1",
}


def parse(html: str) -> List[Dict[str, Any]]:
    """Parse a TechPowerUp CPU DB page into CPU spec rows.

    :param html: raw HTML of a TechPowerUp cpu-specs listing/detail page.
    :returns: list of dicts with keys cpu, cpu_passmark, tdp_w, idle_w,
        name (== cpu), price_gbp (None).

    Not yet materialised — see :data:`SEED_CAPABILITY_METADATA`.
    """
    raise NotImplementedError(
        "techpowerup.parse is a materialiser stub; see "
        "SEED_CAPABILITY_METADATA for the generation brief"
    )


def seed_fallback() -> List[Dict[str, Any]]:
    """Hand-written known APU specs (no retail price)."""
    return [
        {
            "name": "AMD Ryzen 7 8845HS",
            "cpu": "AMD Ryzen 7 8845HS",
            "url": "https://www.techpowerup.com/cpu-specs/ryzen-7-8845hs.c3357",
            "cpu_passmark": 28500,
            "tdp_w": 45.0,
            "idle_w": None,
            "ram_gb": None,
            "storage_gb": None,
            "price_gbp": None,
            "currency_orig": "GBP",
            "price_orig": None,
        },
        {
            "name": "AMD Ryzen 9 8945HS",
            "cpu": "AMD Ryzen 9 8945HS",
            "url": "https://www.techpowerup.com/cpu-specs/ryzen-9-8945hs.c3358",
            "cpu_passmark": 30000,
            "tdp_w": 54.0,
            "idle_w": None,
            "ram_gb": None,
            "storage_gb": None,
            "price_gbp": None,
            "currency_orig": "GBP",
            "price_orig": None,
        },
        {
            "name": "Intel Core Ultra 7 155H",
            "cpu": "Intel Core Ultra 7 155H",
            "url": "https://www.techpowerup.com/cpu-specs/core-ultra-7-155h.c3407",
            "cpu_passmark": 27000,
            "tdp_w": 28.0,
            "idle_w": None,
            "ram_gb": None,
            "storage_gb": None,
            "price_gbp": None,
            "currency_orig": "GBP",
            "price_orig": None,
        },
    ]


__all__ = ["SEED_CAPABILITY_METADATA", "parse", "seed_fallback"]
