#!/bin/bash
echo "========================================="
echo "📅 CRON-JOB.ORG FIX - Output too large"
echo "========================================="
echo ""
echo "The error 'Failed (output too large)' means your"
echo "evolution endpoint returns too much data."
echo ""
echo "Fix: Use the /health endpoint instead of /evolve"
echo ""
echo "NEW CRONJOB SETTINGS:"
echo "────────────────────────────"
echo "• URL: https://your-render-app.onrender.com/health"
echo "• Schedule: Every 5 minutes"
echo "• Method: GET"
echo "• Save response: NO (to prevent output buildup)"
echo ""
echo "For evolution, create a SECOND cronjob:"
echo "────────────────────────────"
echo "• URL: https://your-render-app.onrender.com/evolve"
echo "• Schedule: Every 60 minutes (not 5 minutes)"
echo "• Method: GET"
echo "• Save response: NO"
echo ""
echo "WHY THIS WORKS:"
echo "- /health returns tiny response (fits in cron-job.org limits)"
echo "- Keeps service alive 24/7"
echo "- Evolves hourly instead of every 5 minutes"
echo "- No more output size errors"
