#!/bin/bash
echo "🚀 Deploying DMAI Evolution to Render"
echo "========================================"
echo ""
echo "Step 1: Push code to GitHub"
git add render_evolution.py render_requirements.txt Procfile
git commit -m "Add Render evolution service"
git push
echo ""
echo "Step 2: Go to https://dashboard.render.com"
echo "Step 3: Click 'New +' → 'Web Service'"
echo "Step 4: Connect your GitHub repository"
echo "Step 5: Use these settings:"
echo "   • Name: dmai-evolution"
echo "   • Environment: Python 3"
echo "   • Build Command: pip install -r render_requirements.txt"
echo "   • Start Command: gunicorn render_evolution:app"
echo "   • Instance Type: Free"
echo ""
echo "Step 6: After deployment, your URL will be:"
echo "   https://dmai-evolution.onrender.com"
echo ""
echo "Step 7: Run ./cron_setup.sh for cron-job.org instructions"
