#!/bin/bash
echo "🔑 DMAI Next Session - $(date)"
echo "=================================="
echo ""
echo "📋 Run these commands to start:"
echo "cd /Users/davidmiles/Desktop/dmai-system"
echo "source venv/bin/activate"
echo "./scripts/start_venv_services.sh"
echo "tail -f logs/voice.log"
echo ""
echo "🎯 Priority tasks:"
echo "1. Fix Knowledge Graph health warnings"
echo "2. Fix evolution loop variable error"
echo "3. Add personal API keys to .env"
echo "4. Check for discovered keys with: check-keys"
