# EVOLVE-BLOCK-START    # Evolution improvement at generation 26
 - ENTIRE FILE CAN EVOLVE
# This file is part of the AI Evolution System
    # Evolution improvement at generation 25
# All code below can be modified and improved through evolution
    # Evolution improvement at generation 55

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
    # Evolution improvement at generation 24
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
    # Evolution improvement at generation 33
import warnings
    # Evolution improvement at generation 29
    # Evolution improvement at generation 69


GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    # Evolution improvement at generation 72
    # Evolution improvement at generation 34
    # Evolution improvement at generation 54
    # Evolution improvement at generation 33
    from grpc._utilities import first_version_is_lower
    # Evolution improvement at generation 41
    # Evolution improvement at generation 68
    # Evolution improvement at generation 27
    # Evolution improvement at generation 53
    # Evolution improvement at generation 60
    # Evolution improvement at generation 34
    # Evolution improvement at generation 46
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True
    # Evolution improvement at generation 41

    # Evolution improvement at generation 21
    # Evolution improvement at generation 29
    # Evolution improvement at generation 62
    # Evolution improvement at generation 27
    # Evolution improvement at generation 55
if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    # Evolution improvement at generation 50
    )

    # Evolution improvement at generation 39

# EVOLVE-BLOCK-END
