"""Layer 3 self-bootstrapping seeder for empty core tables.
Auto-generated by SelfRepairOrchestrator. Idempotent (COUNT(*)==0 guard)."""
from __future__ import annotations
import logging, os
from datetime import datetime, timezone
logger = logging.getLogger(__name__)
try: from components.db import safe_open_kdb
except Exception: safe_open_kdb = None  # type: ignore
def _seed() -> None:
    p = os.environ.get("DMAI_KDB_PATH") or next((c for c in ("data/dmai_knowledge.db","dmai_knowledge.db") if os.path.exists(c)), "data/dmai_knowledge.db")
    if safe_open_kdb is None or not os.path.exists(p): return
    ts = datetime.now(timezone.utc).isoformat()
    rows = [
        ("capabilities","INSERT INTO capabilities (name,description,category,capability_type) VALUES (?,?,?,?)",("layer3_seed","Layer3 baseline row","bootstrap","bootstrap")),
        ("insights","INSERT INTO insights (concept,insight_text,confidence,domain,source) VALUES (?,?,?,?,?)",("layer3_bootstrap","Layer3 baseline insight",0.5,"system","layer3")),
        ("suggestions","INSERT INTO suggestions (id,source,title,description,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)",("seed_bootstrap","layer3","Layer3 bootstrap","Baseline suggestion row","pending",ts,ts)),
    ]
    try:
        c = safe_open_kdb(p)
        for t, sql, params in rows:
            try:
                if c.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] == 0:
                    c.execute(sql, params); c.commit()
            except Exception as e: logger.warning(f"empty_tables_seeder {t}: {e}")
        c.close()
    except Exception as e: logger.warning(f"empty_tables_seeder open: {e}")
_seed()
