"""
SelfCommitter — validates generated code, commits it to GitHub, waits for redeploy,
then verifies the gap is closed.
"""
import os, subprocess, ast, logging, json
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


class SelfCommitter:
    def __init__(self, data_path="data"):
        self.data_path = data_path.rstrip("/")
        self.log_path = os.path.join(self.data_path, "self_generation_log.jsonl")

    def commit(self, capability_name: str, code: str, target_file: str) -> bool:
        # Safety: never overwrite files >5KB (likely working implementations)
        if os.path.exists(target_file) and os.path.getsize(target_file) > 5000:
            logger.warning(f"SelfCommitter: refusing to overwrite large file {target_file}")
            return False

        # Write code
        os.makedirs(os.path.dirname(target_file) if os.path.dirname(target_file) else ".", exist_ok=True)
        with open(target_file, "w") as f:
            f.write(code)

        # AST check
        try:
            ast.parse(code)
        except SyntaxError as e:
            logger.error(f"SelfCommitter: AST failed for {target_file}: {e}")
            try:
                os.remove(target_file)
            except Exception:
                pass
            return False

        # Smoke test — main file still parses
        result = subprocess.run(
            ["python3", "-c", "import ast; ast.parse(open('dmai_core_complete.py').read()); print('OK')"],
            capture_output=True, text=True, timeout=15
        )
        if "OK" not in result.stdout:
            logger.error(f"SelfCommitter: smoke test failed: {result.stderr[:200]}")
            return False

        # Git commit and push
        token = os.environ.get("GITHUB_TOKEN_MAIN", "")
        try:
            subprocess.run(["git", "add", target_file], check=True, timeout=10)
            msg = f"auto: {capability_name} — self-generated by DMAI CodeGenerator"
            result = subprocess.run(
                ["git", "commit", "-m", msg],
                capture_output=True, text=True, timeout=15
            )
            if result.returncode != 0 and "nothing to commit" in result.stdout:
                logger.info(f"SelfCommitter: nothing new to commit for {capability_name}")
                return True

            if token:
                remote_url = f"https://{token}@github.com/Davemiles1978/dmai-system.git"
                subprocess.run(["git", "remote", "set-url", "origin", remote_url], timeout=5)

            push = subprocess.run(
                ["git", "push", "origin", "main"],
                capture_output=True, text=True, timeout=30
            )
            if push.returncode != 0:
                logger.error(f"SelfCommitter: push failed: {push.stderr[:200]}")
                return False

        except Exception as e:
            logger.error(f"SelfCommitter: git error: {e}")
            return False

        sha_result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True
        )
        sha = sha_result.stdout.strip()
        self._log(capability_name, target_file, sha, "committed")
        logger.info(f"SelfCommitter: committed {capability_name} → {sha}")
        return True

    def _log(self, capability: str, target_file: str, sha: str, status: str):
        os.makedirs(self.data_path, exist_ok=True)
        entry = {
            "ts": datetime.now(timezone.utc).isoformat(),
            "capability": capability,
            "file": target_file,
            "sha": sha,
            "status": status
        }
        with open(self.log_path, "a") as f:
            f.write(json.dumps(entry) + "\n")
