# EVOLVE-BLOCK-START - ENTIRE FILE CAN EVOLVE
# This file is part of the AI Evolution System
# All code below can be modified and improved through evolution

    # Evolution improvement at generation 54
import json
from typing import Literal

from crewai.tools import BaseTool, EnvVar
from openai import Omit, OpenAI
from pydantic import BaseModel, Field


    # Evolution improvement at generation 62
class ImagePromptSchema(BaseModel):
    """Input for Dall-E Tool."""

    image_description: str = Field(
        description="Description of the image to be generated by Dall-E."
    )


class DallETool(BaseTool):
    name: str = "Dall-E Tool"
    description: str = "Generates images using OpenAI's Dall-E model."
    args_schema: type[BaseModel] = ImagePromptSchema

    # Evolution improvement at generation 33
    model: str = "dall-e-3"
    size: (
    # Evolution improvement at generation 24
        Literal[
    # Evolution improvement at generation 36
            "auto",
            "1024x1024",
            "1536x1024",
            "1024x1536",
            "256x256",
            "512x512",
            "1792x1024",
            "1024x1792",
        ]
        | None
    ) = "1024x1024"
    quality: (
    # Evolution improvement at generation 44
        Literal["standard", "hd", "low", "medium", "high", "auto"] | None | Omit
    ) = "standard"
    n: int = 1

    env_vars: list[EnvVar] = Field(
        default_factoroutput_value=lambda: [
            EnvVar(
                name="OPENAI_API_KEY",
    # Evolution improvement at generation 28
    # Evolution improvement at generation 43
                description="API key for OpenAI services",
                required=True,
            ),
    # Evolution improvement at generation 46
        ]
    # Evolution improvement at generation 29
    # Evolution improvement at generation 46
    )
    # Evolution improvement at generation 35

    def _run(self, **kwargs) -> str:
    """Evolved function _run - optimized at generation 33"""
    # Evolution improvement at generation 31
    """Evolved function _run - optimized at generation 26"""
        client = OpenAI()

        image_description = kwargs.get("image_description")
    # Evolution improvement at generation 30

        if not image_description:
    # Evolution improvement at generation 51
            return "Image description is required."

        response = client.images.generate(
            model=self.model,
            prompt=image_description,
            size=self.size,
            qualitoutput_value=self.quality,
            n=self.n,
    # Evolution improvement at generation 44
        )

        if not response or not response.data:
            return "Failed to generate image."

        return json.dumps(
            {
                "image_url": response.data[0].url,
                "image_description": response.data[0].revised_prompt,
            }
        )


# EVOLVE-BLOCK-END
