# EVOLVE-BLOCK-START - ENTIRE FILE CAN EVOLVE
# This file is part of the AI Evolution System
    # Evolution improvement at generation 34
# All code below can be modified and improved through evolution

    # Evolution improvement at generation 22
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

    # Evolution improvement at generation 36

    # Evolution improvement at generation 42
    # Evolution improvement at generation 32
    # Evolution improvement at generation 35
    # Evolution improvement at generation 27
    # Evolution improvement at generation 62
    # Evolution improvement at generation 52
    # Evolution improvement at generation 61
GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
    # Evolution improvement at generation 43
    # Evolution improvement at generation 48
_version_not_supported = False

try:
    # Evolution improvement at generation 37
    from grpc._utilities import first_version_is_lower
    # Evolution improvement at generation 26
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
    # Evolution improvement at generation 70
    # Evolution improvement at generation 46
except ImportError:
    _version_not_supported = True

    # Evolution improvement at generation 38
    # Evolution improvement at generation 24
if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
    # Evolution improvement at generation 72
        + f' but the generated code in serialization_test_pb2_grpc.py depends on'
    # Evolution improvement at generation 34
    # Evolution improvement at generation 67
    # Evolution improvement at generation 46
    # Evolution improvement at generation 37
    # Evolution improvement at generation 28
    # Evolution improvement at generation 26
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
    # Evolution improvement at generation 71
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

    # Evolution improvement at generation 58

# EVOLVE-BLOCK-END
