"""Static manifest of all built-in DMAI components.

The registry loads this manifest at boot so every known component is visible
even before it is instantiated. Adapters wrap existing repo modules; agents are
native :class:`BaseComponent` implementations.
"""

from __future__ import annotations

from typing import Any

BUILT_IN_COMPONENTS: list[dict[str, Any]] = [
    # ---- Adapters around existing components ---------------------------- #
    {
        "id": "ai_hub",
        "name": "AI Integration Hub",
        "version": "1.0.0",
        "plane": "tool",
        "capabilities": ["llm_query", "multi_model", "synthesis"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.ai_hub:AIHubAdapter",
        "status": "enabled",
    },
    {
        "id": "alex_riviera",
        "name": "Alex Riviera Content Engine",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["content_generation", "book_writing", "publishing"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.adapters.alex_riviera:AlexRivieraAdapter",
        "status": "enabled",
    },
    {
        "id": "evolution_engine",
        "name": "Stage-Aware Evolution Engine",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["learning", "self_evolution", "kpi_tracking"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.adapters.evolution:EvolutionAdapter",
        "status": "enabled",
    },
    {
        "id": "self_funding",
        "name": "Self-Funding Orchestrator",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["revenue_discovery", "funding_phases", "strategy"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.adapters.funding:FundingAdapter",
        "status": "enabled",
    },
    {
        "id": "master_control",
        "name": "Master Control",
        "version": "1.0.0",
        "plane": "governance",
        "capabilities": ["goal_setting", "risk_assessment", "kill_switch"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.master_control:MasterControlAdapter",
        "status": "enabled",
    },
    {
        "id": "wealth_trading",
        "name": "Wealth Trading Engine",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["trading", "positions", "performance"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.wealth_trading:WealthTradingAdapter",
        "status": "disabled",
    },
    # ---- Phase / domain components registered as available-not-loaded --- #
    {
        "id": "research",
        "name": "Research Orchestrator",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["research", "url_learning"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.adapters.research:ResearchAdapter",
        "status": "disabled",
    },
    {
        "id": "media_studio",
        "name": "Media Production Studio",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["media", "avatar", "video"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.media:MediaAdapter",
        "status": "disabled",
    },
    {
        "id": "consciousness_tracker",
        "name": "Consciousness Tracker",
        "version": "1.0.0",
        "plane": "knowledge",
        "capabilities": ["consciousness", "global_workspace"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.consciousness:ConsciousnessAdapter",
        "status": "disabled",
    },
    {
        "id": "trading_engine",
        "name": "Trading Engine",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["trading", "analysis"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.adapters.wealth_trading:WealthTradingAdapter",
        "status": "disabled",
    },
    # ---- Native OPAR agents -------------------------------------------- #
    {
        "id": "market_research_agent",
        "name": "Market Research Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["market_research", "trend_analysis"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.market_research:MarketResearchAgent",
        "status": "enabled",
    },
    {
        "id": "offer_design_agent",
        "name": "Offer Design Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["offer_design", "pricing"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.offer_design:OfferDesignAgent",
        "status": "enabled",
    },
    {
        "id": "outreach_agent",
        "name": "Outreach Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["outreach", "personalization"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.outreach:OutreachAgent",
        "status": "enabled",
    },
    {
        "id": "landing_page_agent",
        "name": "Landing Page Builder Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["landing_page", "html_generation", "ab_testing"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.landing_page_builder:LandingPageBuilderAgent",
        "status": "enabled",
    },
    {
        "id": "analytics_agent",
        "name": "Analytics Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["analytics", "reporting"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.analytics:AnalyticsAgent",
        "status": "enabled",
    },
    {
        "id": "coding_agent",
        "name": "Coding Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["code_generation", "self_extension"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.coding:CodingAgent",
        "status": "enabled",
    },
    {
        "id": "qa_critic_agent",
        "name": "QA Critic Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["quality_review", "scoring"],
        "dependencies": ["ai_hub"],
        "config_schema": {},
        "entry_point": "dmai.agents.qa_critic:QACriticAgent",
        "status": "enabled",
    },
    {
        "id": "compliance_agent",
        "name": "Compliance Agent",
        "version": "1.0.0",
        "plane": "governance",
        "capabilities": ["policy_review", "approval"],
        "dependencies": [],
        "config_schema": {},
        "entry_point": "dmai.agents.compliance:ComplianceAgent",
        "status": "enabled",
    },
    {
        "id": "finance_controller_agent",
        "name": "Finance Controller Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["budgeting", "spend_control", "reporting"],
        "dependencies": ["self_funding"],
        "config_schema": {},
        "entry_point": "dmai.agents.finance_controller:FinanceControllerAgent",
        "status": "enabled",
    },
    {
        "id": "upgrade_lab_agent",
        "name": "Upgrade Lab Agent",
        "version": "1.0.0",
        "plane": "agent",
        "capabilities": ["benchmarking", "model_evaluation", "self_upgrade"],
        "dependencies": ["ai_hub", "evolution_engine"],
        "config_schema": {},
        "entry_point": "dmai.agents.upgrade_lab:UpgradeLabAgent",
        "status": "enabled",
    },
]


def get_manifest_entry(component_id: str) -> dict[str, Any] | None:
    """Return the manifest entry for *component_id*, or ``None``."""
    for entry in BUILT_IN_COMPONENTS:
        if entry["id"] == component_id:
            return dict(entry)
    return None
